export const ERROR_CODES = {
  DB_ERROR: "DB_ERROR",

  AUTH_EMAIL_REQUIRED: "AUTH_EMAIL_REQUIRED",
  AUTH_PASSWORD_REQUIRED: "AUTH_PASSWORD_REQUIRED",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",

  EVENT_INVALID_PAYLOAD: "EVENT_INVALID_PAYLOAD",
  EVENT_ID_REQUIRED: "EVENT_ID_REQUIRED",
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  EVENT_DUPLICATE_RESOURCE: "EVENT_DUPLICATE_RESOURCE",

  VALORACION_INVALID_SCORE: "VALORACION_INVALID_SCORE",
  VALORACION_ALREADY_EXISTS: "VALORACION_ALREADY_EXISTS",
  VALORACION_NOT_FOUND_OR_FORBIDDEN: "VALORACION_NOT_FOUND_OR_FORBIDDEN",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export function statusFromErrorCode(code?: string): number {
  switch (code) {
    case ERROR_CODES.AUTH_EMAIL_REQUIRED:
    case ERROR_CODES.AUTH_PASSWORD_REQUIRED:
    case ERROR_CODES.EVENT_INVALID_PAYLOAD:
    case ERROR_CODES.EVENT_ID_REQUIRED:
    case ERROR_CODES.VALORACION_INVALID_SCORE:
      return 400;

    case ERROR_CODES.AUTH_EMAIL_ALREADY_EXISTS:
    case ERROR_CODES.EVENT_DUPLICATE_RESOURCE:
    case ERROR_CODES.VALORACION_ALREADY_EXISTS:
      return 409;

    case ERROR_CODES.EVENT_NOT_FOUND:
    case ERROR_CODES.VALORACION_NOT_FOUND_OR_FORBIDDEN:
      return 404;

    case ERROR_CODES.DB_ERROR:
      return 500;

    default:
      return 400;
  }
}
