/**
 * Shared utilities for building and parsing event URLs.
 *
 * URL format: /eventos/${idPublico}-${slugifiedName}
 *   e.g. /eventos/a1b2c3d4e5f6-semana-santa-en-bucaramanga
 *
 * The `id_publico_evento` is a 12-char lowercase hex string generated by the
 * DB trigger (SHA-256 of the numeric ID). It is never a sequential integer,
 * so it does not expose internal data.
 *
 * Fallback: /eventos when idPublico is unavailable.
 */

/** 12-character lowercase hex — matches the DB trigger output */
const ID_PUBLICO_REGEX = /^[0-9a-f]{12}$/i

function slugifyEventName(value: string | null | undefined): string {
  return (
    String(value || "evento")
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "") || "evento"
  )
}

/**
 * Builds a public, ID-free event URL.
 * Format: /eventos/${idPublico}-${slugifiedName}
 * Falls back to /eventos when idPublico is unavailable.
 */
export function buildEventUrl(
  idPublico: string | null | undefined,
  nombreEvento: string | null | undefined,
  fallbackId: number
): string {
  const cleaned = String(idPublico ?? "").trim()
  if (ID_PUBLICO_REGEX.test(cleaned)) {
    const nameSlug = slugifyEventName(nombreEvento)
    return `/eventos/${cleaned}-${nameSlug}`
  }
  void fallbackId
  return "/eventos"
}

export type ParsedEventSlug = {
  idPublico: string | null
  numericId: number | null
}

/**
 * Extracts idPublico or numericId from a route slug.
 * Handles:
 *   "a1b2c3d4e5f6-semana-santa"  → { idPublico: "a1b2c3d4e5f6", numericId: null }
 *   "a1b2c3d4e5f6"              → { idPublico: "a1b2c3d4e5f6", numericId: null }
 *   "123"                       → { idPublico: null, numericId: 123 }
 */
export function parseEventSlug(slug: string): ParsedEventSlug {
  const trimmed = slug.trim()

  const candidate = trimmed.substring(0, 12)
  if (
    ID_PUBLICO_REGEX.test(candidate) &&
    (trimmed.length === 12 || trimmed[12] === "-")
  ) {
    return { idPublico: candidate, numericId: null }
  }

  const num = Number(trimmed)
  if (Number.isFinite(num) && num > 0) {
    return { idPublico: null, numericId: num }
  }

  return { idPublico: null, numericId: null }
}
