import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import DeferredGlobalUI from "@/components/deferred-global-ui"
import SecurityProvider from "@/components/shared/SecurityProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Time2Go",
  description: "Generated by create next app",
  icons: { icon: [{ url: "/logo.svg", type: "image/svg+xml" }] },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const rawTheme = cookieStore.get("theme")?.value
  const initialTheme = rawTheme === "dark" || rawTheme === "light" ? rawTheme : "light"
  const htmlClassName = initialTheme === "dark" ? "dark" : undefined

  return (
    <html lang="en" className={htmlClassName} style={{ colorScheme: initialTheme }}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SecurityProvider>
          {children}
          <DeferredGlobalUI />
        </SecurityProvider>
      </body>
    </html>
  );
}