import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CookieConsent from "@/components/cookie-consent"
import { SessionMonitor } from "@/components/session-monitor"
import { ThemeToggle } from "@/components/theme-toggle"
import SecurityProvider from "@/components/shared/SecurityProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Time2Go",
  description: "Generated by create next app",
  icons: { icon: [{ url: "/logo.svg", type: "image/svg+xml" }] },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SecurityProvider>
          <SessionMonitor />
          {children}
          <ThemeToggle />
          <CookieConsent />
        </SecurityProvider>
      </body>
    </html>
  );
}